# Generated by Django 3.2.9 on 2021-12-06 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleveSanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.IntegerField(default=0, unique=True)),
                ('temprature', models.FloatField()),
                ('humidite', models.FloatField()),
                ('pressionAir', models.FloatField()),
                ('oxydeCarbone', models.FloatField()),
                ('particule', models.FloatField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.zone')),
            ],
        ),
    ]
