# Generated by Django 3.2.9 on 2021-12-06 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveillanceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbDronesActives', models.IntegerField(default=0)),
                ('nbDronesEnPanne', models.IntegerField(default=0)),
                ('nbDronesEnRechargement', models.IntegerField(default=0)),
                ('detectionIncendie', models.BooleanField(default=False)),
                ('auditConformite', models.BooleanField(default=False)),
                ('detectionForme', models.CharField(choices=[('aucune', 'Aucune'), ('personnel non identifiée', 'Personnelnonidentifiee'), ('objet non identifiee', 'Objetnonidentifiee')], default='aucune', max_length=50)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zone.zone')),
            ],
        ),
    ]
