# Generated by Django 3.2.9 on 2021-11-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.TextField()),
                ('prenom', models.TextField()),
                ('etat', models.CharField(choices=[('actif', 'Actif'), ('repos', 'Repos'), ('arret maladie', 'Arret'), ('congé', 'Conge')], default='actif', max_length=14)),
                ('service', models.CharField(choices=[('commercial', 'Commercial'), ('finance et gestion', 'Finance'), ('ressources humaines', 'Ressource'), ('juridique', 'Juridique'), ('logistique', 'Logistique'), ('assistance commerciale', 'Assistancecom'), ('direction générale', 'Direction'), ('maintenance', 'Maintenance'), ('achats', 'Achats'), ('cyber sécurité', 'Cyber'), ('recherche et développement', 'Recherche'), ('informatique', 'Informatique'), ('qualité', 'Qualite'), ('collecte', 'Collecte'), ('marketing', 'Marketing'), ('industriel', 'Industriel'), ('assistance technique', 'Assistancetech'), ('analyse des données', 'Analyse')], max_length=30)),
                ('frequenceQardiaque', models.FloatField()),
                ('tauxSudation', models.FloatField()),
            ],
        ),
    ]
