# Generated by Django 3.2.9 on 2021-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='id',
        ),
        migrations.AddField(
            model_name='personnel',
            name='identifiant',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
