# Generated by Django 3.2.9 on 2021-12-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20211119_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='frequenceQardiaque',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='tauxSudation',
            field=models.FloatField(blank=True),
        ),
    ]
